name: Test Github Lint
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  Test-Github-Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: composer:v2
          extensions: gd
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Install Drupal
        run: |
          cd ../
          mkdir drupal
          cd drupal
          cp ${GITHUB_WORKSPACE}/tests/fixtures.drainpipe-external-test-project/composer.json .
          cp ${GITHUB_WORKSPACE}/tests/fixtures.drainpipe-external-test-project/Taskfile.yml .
          composer install
      - name: Copy our own workflows
        run: |
          cp -r ${GITHUB_WORKSPACE}/.github ../drupal
      - name: Run github lint tests
        run: |
          cd ../drupal
          ./vendor/bin/task github:actions:lint
